[package]
name = "shadow-crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.6"
select = "0.6.0"
tokio = { version = "1.0", features = ["full"] }

